CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;
CREATE TABLE meta (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE players (
 id BIGINT PRIMARY KEY, name TEXT NOT NULL, number TEXT, active BOOLEAN NOT NULL DEFAULT FALSE,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE sessions (
 id BIGINT PRIMARY KEY, title TEXT NOT NULL DEFAULT '', start_utc TIMESTAMPTZ NOT NULL,
 end_utc TIMESTAMPTZ, local_date DATE NOT NULL, source_labels JSONB NOT NULL DEFAULT '[]',
 classification TEXT NOT NULL DEFAULT 'unknown' CHECK(classification IN ('practice','game','unknown')),
 reviewed BOOLEAN NOT NULL DEFAULT FALSE, status TEXT NOT NULL DEFAULT 'preliminary',
 expected_players INTEGER CHECK(expected_players >= 0), source_hash TEXT NOT NULL DEFAULT '',
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), source_json JSONB NOT NULL DEFAULT '{}',
 assignment_complete BOOLEAN NOT NULL DEFAULT FALSE, sync_complete BOOLEAN NOT NULL DEFAULT FALSE,
 removed_upstream BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE stats (
 session_id BIGINT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
 player_id BIGINT NOT NULL REFERENCES players(id), metrics_json JSONB NOT NULL,
 missing_json JSONB NOT NULL DEFAULT '[]', legacy BOOLEAN NOT NULL DEFAULT FALSE,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), raw_json JSONB NOT NULL DEFAULT '{}',
 PRIMARY KEY(session_id,player_id)
);
CREATE TABLE assignments (
 session_id BIGINT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
 player_id BIGINT NOT NULL REFERENCES players(id), source_json JSONB NOT NULL DEFAULT '{}',
 PRIMARY KEY(session_id,player_id)
);
CREATE TABLE phases (
 id BIGINT PRIMARY KEY, session_id BIGINT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
 title TEXT NOT NULL DEFAULT '', start_utc TIMESTAMPTZ, end_utc TIMESTAMPTZ,
 source_labels JSONB NOT NULL DEFAULT '[]', source_json JSONB NOT NULL DEFAULT '{}',
 valid BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE phase_stats (
 phase_id BIGINT NOT NULL REFERENCES phases(id) ON DELETE CASCADE,
 player_id BIGINT NOT NULL REFERENCES players(id), metrics_json JSONB NOT NULL,
 missing_json JSONB NOT NULL DEFAULT '[]', raw_json JSONB NOT NULL DEFAULT '{}',
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), PRIMARY KEY(phase_id,player_id)
);
CREATE TABLE reviews (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 session_id BIGINT NOT NULL REFERENCES sessions(id), classification TEXT NOT NULL,
 reason TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), actor_id TEXT,
 provenance TEXT NOT NULL DEFAULT 'local'
);
CREATE TABLE reports (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 session_id BIGINT NOT NULL REFERENCES sessions(id), version INTEGER NOT NULL CHECK(version>0),
 source_hash TEXT NOT NULL, payload_json JSONB NOT NULL,
 generated_at TIMESTAMPTZ NOT NULL, UNIQUE(session_id,version)
);
CREATE TABLE jobs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 kind TEXT NOT NULL CHECK(kind IN ('sync','report','index','embeddings')),
 payload_json JSONB NOT NULL DEFAULT '{}', dedupe_key TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','running','completed','partial','failed')),
 message TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), attempts INTEGER NOT NULL DEFAULT 0,
 result_json JSONB, worker_id TEXT, lease_until TIMESTAMPTZ, claim_token TEXT
);
CREATE UNIQUE INDEX jobs_active_dedupe ON jobs(kind,dedupe_key) WHERE status IN ('queued','running');
CREATE TABLE sync_runs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 job_id BIGINT REFERENCES jobs(id) ON DELETE SET NULL, start_date DATE NOT NULL, end_date DATE NOT NULL,
 status TEXT NOT NULL CHECK(status IN ('running','completed','failed','partial')),
 started_at TIMESTAMPTZ NOT NULL DEFAULT now(), finished_at TIMESTAMPTZ,
 failure_count INTEGER NOT NULL DEFAULT 0, result_json JSONB NOT NULL DEFAULT '{}',
 worker_id TEXT, claim_token TEXT, CHECK(start_date<=end_date)
);
CREATE TABLE documents (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 title TEXT NOT NULL, body TEXT NOT NULL, kind TEXT NOT NULL,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), content_hash TEXT NOT NULL,
 embedding_json JSONB, embedding_model TEXT, embedding public.vector,
 embedding_dimensions INTEGER, owner_id TEXT,
 search_vector TSVECTOR GENERATED ALWAYS AS
   (to_tsvector('english', coalesce(title,'') || ' ' || coalesce(body,''))) STORED
);
CREATE UNIQUE INDEX documents_seed_identity ON documents(title,kind) WHERE kind<>'coach_note';
CREATE INDEX documents_search ON documents USING GIN(search_vector);
CREATE TABLE chat_messages (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 conversation_id TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('user','assistant')),
 content TEXT NOT NULL, response_json JSONB, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 owner_id TEXT NOT NULL DEFAULT 'local'
);
CREATE TABLE import_manifests (
 fingerprint TEXT PRIMARY KEY, source_name TEXT NOT NULL,
 counts_json JSONB NOT NULL, verification_json JSONB NOT NULL,
 completed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_sessions_date ON sessions(local_date,start_utc);
CREATE INDEX idx_stats_player ON stats(player_id,session_id);
CREATE INDEX idx_phases_session ON phases(session_id,start_utc);
CREATE INDEX idx_phase_stats_player ON phase_stats(player_id,phase_id);
CREATE INDEX idx_jobs_status ON jobs(status,id);
CREATE INDEX idx_sync_runs_coverage ON sync_runs(status,start_date,end_date);
CREATE INDEX chat_conversation ON chat_messages(owner_id,conversation_id,id);
